### ISSUE TITLE
Pub serve in DDC mode doesn't work for project from web/subdir

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/pub#1622]
_From @alexander-doroshko on May 24, 2017 13:12_

Environment: Windows 10, Dart SDK 1.24.0-dev.5.0. 
Steps:
- Unzip the [attached project](https://github.com/dart-lang/sdk/files/1025571/anagram_in_subdir.zip), run `pub get`.
- Run `pub serve` from the command line.
- Open `http://localhost:8080/subdir/index.html` in Chrome. The app works just fine.
- Restart pub in DDC mode: `pub serve --compiler=dartdevc`.
- Open `http://localhost:8080/subdir/index.html` in Chrome. The app doesn't load.

_Copied from original issue: dart-lang/sdk#29704_

**Comment by jakemac53** [comment]
This has been fixed already actually, the 1.24.0-dev.6.0 release should work (I also tested this project with my locally built sdk and it works).

**Comment by alexander-doroshko** [comment]
FWIW the problem is still reproduced with 
```
dartsdk-windows-x64-release.zip	24-May-2017 13:42	58.7M	"a5033a1906eb6a6b9113995ec6c449ff"
```
from http://gsdview.appspot.com/dart-archive/channels/dev/raw/1.24.0-dev.6.0/sdk/

**Comment by jakemac53** [comment]
It is probably a windows specific issue, investigating further

**Comment by jakemac53** [comment]
Alright, confirmed this is reproducible on windows. It looks like the library name for the module is missing the subdirectory portion on windows, so we try to call main() on a non-existing library.

**Comment by jakemac53** [comment]
Fwiw, resolving https://github.com/dart-lang/sdk/issues/27262 would likely solve this issue.

**Comment by jakemac53** [comment]
Fixed by https://codereview.chromium.org/2899363002/, working on a cherry pick now
